spring:
  profiles:
    active: dev
---
# Spring的配置
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: springcloud-eureka
# Eureka的配置
eureka:
  instance:
    hostname: localhost   # Eureka服务端的实例名称
  client:
    register-with-eureka: false   # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # fetch-registry为false，表示自己为注册中心
    service-url: # 监控页面
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
---
# Spring的配置
server:
  port: 7001

spring:
  profiles: test
  application:
    name: springcloud-eureka
# Eureka的配置
eureka:
  instance:
    hostname: localhost   # Eureka服务端的实例名称
  client:
    register-with-eureka: false   # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # fetch-registry为false，表示自己为注册中心
    service-url: # 监控页面
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
