spring:
  profiles:
    active: dev

---
server:
  port: 8201
# Spring的配置
spring:
  profiles: dev
  apllication:
    name: springcloud-provider-dept

# Eureka的配置
eureka:
  client:
    service-url: # 监控页面
      defaultZone: http://localhost:7001/eureka/
      
---
server:
  port: 8202
# Spring的配置
spring:
  profiles: test
  apllication:
    name: springcloud-provider-dept

# Eureka的配置
eureka:
  client:
    service-url: # 监控页面
      defaultZone: http://localhost:7001/eureka/
